//
// Copyright © 2025 Anonyome Labs, Inc. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//

import Foundation

public let defaultEmailAddressesLimit = 10

/// input object for getting an email address using `SudoEmailClient`
public struct ListEmailAddressesInput: Equatable {

    /// The number of items to return.  Will be defaulted if omitted.
    public let limit: Int?

    /// A token generated by a previous call.
    public let nextToken: String?

    public init(limit: Int? = defaultEmailAddressesLimit, nextToken: String? = nil) {
        self.limit = limit
        self.nextToken = nextToken
    }
}
