//
// Copyright © 2025 Anonyome Labs, Inc. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//

import Foundation

/// Input object for listing draft email message metadata for an email address using `SudoEmailClient`.
public struct ListDraftEmailMessageMetadataForEmailAddressIdInput: Equatable {

    /// The identifier of the email address associated with the draft email messages.
    public let emailAddressId: String

    /// The number of items to return. If omitted, the default of 10 will be used.
    public let limit: Int?

    /// A pagination token generated by a previous call.
    public let nextToken: String?

    public init(
        emailAddressId: String,
        limit: Int? = nil,
        nextToken: String? = nil
    ) {
        self.emailAddressId = emailAddressId
        self.limit = limit
        self.nextToken = nextToken
    }
}
