//
// Copyright © 2022 Anonyome Labs, Inc. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//

import Foundation

public let defaultEmailAddressesLimit = 10

/// input object for getting an email address using `SudoEmailClient`
public struct ListEmailAddressesInput: Equatable {

    /// Determines how the email address will be fetched. Default usage is `remoteOnly`.
    public let cachePolicy: CachePolicy?

    /// The number of items to return.  Will be defaulted if omitted.
    public let limit: Int?

    /// A token generated by a previous call.
    public let nextToken: String?

    public init(
        cachePolicy: CachePolicy? = .remoteOnly,
        limit: Int? = defaultEmailAddressesLimit,
        nextToken: String? = nil
    ) {
        self.cachePolicy = cachePolicy
        self.limit = limit
        self.nextToken = nextToken
    }
}
