//
// Copyright © 2022 Anonyome Labs, Inc. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//

import Foundation

public let defaultEmailMessageLimit = 10

/// input object for listing email messages for an email address using `SudoEmailClient`
public struct ListEmailMessagesForEmailAddressInput: Equatable {

    /// The unique identifier of email address to retrieve messages for.
    public let emailAddressId: String

    /// Determines how the email address will be fetched. Default usage is `remoteOnly`.
    public let cachePolicy: CachePolicy?

    /// Email messages created within the date range inclusive will be fetched.
    public let dateRange: DateRange?

    /// The direction in which the email messages are sorted. Defaults to descending.
    public let sortOrder: SortOrder?

    /// The number of items to return.  If omitted, the default of 10 will be used.
    public let limit: Int?

    /// A pagination token generated by a previous call.
    public let nextToken: String?

    public init(
        emailAddressId: String,
        cachePolicy: CachePolicy? = .remoteOnly,
        dateRange: DateRange? = nil,
        sortOrder: SortOrder? = nil,
        limit: Int? = defaultEmailMessageLimit,
        nextToken: String? = nil
    ) {
        self.emailAddressId = emailAddressId
        self.cachePolicy = cachePolicy
        self.dateRange = dateRange
        self.sortOrder = sortOrder
        self.limit = limit
        self.nextToken = nextToken
    }
}
