//
// Copyright © 2025 Anonyome Labs, Inc. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//

import Foundation

/// Input object for listing draft email message metadata using `SudoEmailClient`.
public struct ListDraftEmailMessageMetadataInput: Equatable {

    /// The number of items to return. If omitted, the default of 10 will be used.
    public let limit: Int?

    /// A pagination token generated by a previous call.
    public let nextToken: String?

    public init(
        limit: Int? = nil,
        nextToken: String? = nil
    ) {
        self.limit = limit
        self.nextToken = nextToken
    }
}
