//
// Copyright © 2025 Anonyome Labs, Inc. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//

import Foundation

/// input object for listing email folders for an email address using `SudoEmailClient`
public struct ListEmailFoldersForEmailAddressIdInput: Equatable {

    /// The unique identifier of email address to retrieve folders for.
    public let emailAddressId: String

    /// Determines how the email folders will be fetched. Default usage is `remoteOnly`.
    public let cachePolicy: CachePolicy?

    /// The number of items to return.  If omitted, the default of 10 will be used.
    public let limit: Int?

    /// A pagination token generated by a previous call.
    public let nextToken: String?

    public init(
        emailAddressId: String,
        cachePolicy: CachePolicy? = .remoteOnly,
        limit: Int? = defaultEmailMessageLimit,
        nextToken: String? = nil
    ) {
        self.emailAddressId = emailAddressId
        self.cachePolicy = cachePolicy
        self.limit = limit
        self.nextToken = nextToken
    }
}
