//
// Copyright © 2025 Anonyome Labs, Inc. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//

import Foundation

/// Input object for listing scheduled draft messages for an email address
public struct ListScheduledDraftMessagesForEmailAddressIdInput {

    /// The identifier of the email address to list for
    public let emailAddressId: String

    /// The number of items to return.  If omitted, the default of 10 will be used.
    public let limit: Int?

    /// A pagination token generated by a previous call.
    public let nextToken: String?

    /// Properties used to filter the results.
    public let filter: ScheduledDraftMessageFilter?

    public init(
        emailAddressId: String,
        limit: Int?,
        nextToken: String?,
        filter: ScheduledDraftMessageFilter?
    ) {
        self.emailAddressId = emailAddressId
        self.limit = limit
        self.nextToken = nextToken
        self.filter = filter
    }
}
