//
// Copyright © 2025 Anonyome Labs, Inc. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//

import Foundation

public let defaultEmailMessageLimit = 10

/// input object for listing email messages for an email address using `SudoEmailClient`
public struct ListEmailMessagesForEmailAddressInput: Equatable {

    /// The unique identifier of email address to retrieve messages for.
    public let emailAddressId: String

    /// Email messages matching the specified date range inclusive will be fetched.
    public let dateRange: EmailMessageDateRange?

    /// Determines how the email address will be fetched. Default usage is `remoteOnly`.
    public let cachePolicy: CachePolicy?

    /// The direction in which the email messages are sorted. Defaults to descending.
    public let sortOrder: SortOrder?

    /// The number of items to return.  If omitted, the default of 10 will be used.
    public let limit: Int?

    /// A pagination token generated by a previous call.
    public let nextToken: String?

    /// Whether to include deleted messages or not. Defaults to false.
    public let includeDeletedMessages: Bool?

    public init(
        emailAddressId: String,
        dateRange: EmailMessageDateRange? = nil,
        cachePolicy: CachePolicy? = .remoteOnly,
        sortOrder: SortOrder? = nil,
        limit: Int? = defaultEmailMessageLimit,
        nextToken: String? = nil,
        includeDeletedMessages: Bool? = false
    ) {
        self.emailAddressId = emailAddressId
        self.dateRange = dateRange
        self.cachePolicy = cachePolicy
        self.sortOrder = sortOrder
        self.limit = limit
        self.nextToken = nextToken
        self.includeDeletedMessages = includeDeletedMessages
    }
}
